name: Flutter Web Build To Github Page
# 表示当 main 分支上有 push 时触发
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    # 表示运行在 ubuntu 最新版本的机器上
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: build
        # 表示使用 flutter-action 这个脚本来构建
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      # 按照下面的顺序执行打包命令
      - run: flutter pub get
      - run: flutter channel master
      - run: flutter upgrade
      - run: flutter config --enable-web
      # 构建 web 产物
      - run: flutter build web --base-href=web_flutter

      - name: deploy
        # 表示使用 actions-gh-page 这个脚本来部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 这里直接这样写就可以，github 会自动生成用在 Actions 的 GITHUB_TOKEN
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 发布的分支
          PUBLISH_BRANCH: gh-pages
          # 发布的内容，在 build/web 目录下
          publish_dir: ./build/web