name: 'Deploying Flutter web app to github pages'
description: 'Automates the build and deployment of your Flutter web app on Github gh pages'
author: 'bluefireteam'

branding:
  color: blue
  icon: code

inputs:
  webRenderer:
    description: 'Which web renderer to be used, default is auto'
    required: false
    default: auto
  workingDir:
    description: 'The directory where the project is (default .)'
    required: false
    default: .
  targetBranch:
    required: false
    default: gh-pages
  baseHref:
    description: 'base href (if applicable)'
    required: false
    default: "/web_flutter/"
  customArgs:
    description: 'Custom args like: --dart-define="simple=example"'
    required: false
    default:

runs:
  using: 'composite'
  steps:
    - run: flutter config --enable-web
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: flutter build web --release --base-href ${{inputs.baseHref}}
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - name: deploy
        # 表示使用 actions-gh-page 这个脚本来部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 这里直接这样写就可以，github 会自动生成用在 Actions 的 GITHUB_TOKEN
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 发布的分支
          PUBLISH_BRANCH: gh-pages
          # 发布的内容，在 build/web 目录下
          publish_dir: ./build/web